ALTER TABLE users ADD COLUMN name TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN email_verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN image TEXT;
ALTER TABLE users ADD COLUMN updated_at TEXT;
UPDATE users SET name=email,updated_at=created_at;
ALTER TABLE tenants ADD COLUMN slug TEXT;
ALTER TABLE tenants ADD COLUMN logo TEXT;
ALTER TABLE tenants ADD COLUMN metadata TEXT;
UPDATE tenants SET slug='workspace-' || id;
CREATE UNIQUE INDEX tenants_slug ON tenants(slug);
ALTER TABLE tenant_members ADD COLUMN id TEXT;
ALTER TABLE tenant_members ADD COLUMN created_at TEXT;
UPDATE tenant_members SET id=tenant_id || ':' || user_id,created_at=strftime('%Y-%m-%dT%H:%M:%fZ','now');
CREATE UNIQUE INDEX tenant_members_id ON tenant_members(id);
CREATE INDEX tenant_members_user ON tenant_members(user_id);
CREATE TABLE auth_sessions (id TEXT PRIMARY KEY, token TEXT NOT NULL UNIQUE, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, ip_address TEXT, user_agent TEXT, active_organization_id TEXT);
CREATE INDEX auth_sessions_user ON auth_sessions(user_id);
CREATE TABLE auth_accounts (id TEXT PRIMARY KEY, account_id TEXT NOT NULL, provider_id TEXT NOT NULL, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, access_token TEXT, refresh_token TEXT, id_token TEXT, access_token_expires_at TEXT, refresh_token_expires_at TEXT, scope TEXT, password TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(provider_id,account_id));
CREATE INDEX auth_accounts_user ON auth_accounts(user_id);
CREATE TABLE auth_verifications (id TEXT PRIMARY KEY, identifier TEXT NOT NULL, value TEXT NOT NULL, expires_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX auth_verifications_identifier ON auth_verifications(identifier);
CREATE TABLE auth_rate_limits (id TEXT PRIMARY KEY, key TEXT NOT NULL UNIQUE, count INTEGER NOT NULL, last_request INTEGER NOT NULL);
CREATE TABLE auth_invitations (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL REFERENCES tenants(id), email TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('admin','analyst','viewer')), status TEXT NOT NULL, inviter_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX auth_invitations_org ON auth_invitations(organization_id,status);
CREATE INDEX auth_invitations_email ON auth_invitations(email,status);
